publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: latest
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: master
deploy:
  ssh:
    host: dev.huyi.so
    user: root
    when:
      branch: master
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys
      - docker run --rm --volumes-from=static registry.aliyuncs.com/xiaolu-img/xiaolusys python manage.py collectstatic --noinput
      - docker rm -f gunicorn 
      - docker run --name=gunicorn -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000 registry.aliyuncs.com/xiaolu-img/xiaolusys gunicorn_django -k gevent -c taobao_gunicorn_conf.py
